[BREAKINGCHANGE] generateChartsTheme can override any value
perses/perses pull request #1558
Opened 2023-10-31 08:21 UTC by celian-garcia

# Description

``generateChartsTheme`` function is very practical, but I would like to propose the ability to override a bit more fields. This is a breaking change as the function is exposed and potentially used by users? @jgbernalp are you using it in Redhat?

# Screenshots

# Checklist

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `IGNORE`.
- [ ] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [ ] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [ ] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [ ] Visual tests are stable and unlikely to be flaky. See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests) and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

2023-10-31 10:00 UTC, jgbernalp requested changes

2023-10-31 10:00 UTC, jgbernalp commented on ui/components/src/utils/theme-gen.ts
> -  tooltipPortalContainerId?: string
Do we need to remove this, this was part of a bugfix: https://github.com/perses/perses/pull/1309, does this still the case?

2023-10-31 11:02 UTC, jgbernalp approved these changes

2023-10-31 11:03 UTC, jgbernalp approved these changes
LGTM

2023-10-31 16:45 UTC, Gladorme approved these changes
LGTM 👍

2023-11-11 15:06 UTC, sjcobb approved these changes
🙌

2023-11-13 10:01 UTC, AntoineThebaud approved these changes

2023-11-13 10:28 UTC, Nexucis approved these changes

2023-11-13 10:37 UTC, Nexucis commented
if you can fix the tests @celian-garcia then we will be able to finally merge this nice PR :). Thanks !

2023-11-13 10:42 UTC, celian-garcia commented
> if you can fix the tests @celian-garcia then we will be able to finally merge this nice PR :). Thanks !

Sure yeah, we start the sprint today so I have more bandwidth

2023-11-13 11:07 UTC, merged