[ENHANCEMENT] Update configuration md file also oauth helper
perses/perses pull request #2329
Opened 2024-10-11 17:25 UTC by Labiote

# Description

Pull request for : [#2322](https://github.com/perses/perses/issues/2322)

Updating `configuration.md` to have correct parameters names. Also updating `oauth-configuration-helpers.md` to have an example of keycloak authentication with no tls. Also updating TLSConfig builder to use MinVersion and MaxVersion parameters instead of default ones.

# Screenshots

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [ ] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [ ] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [ ] Visual tests are stable and unlikely to be flaky.
  See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests)
  and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues
  include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

2024-10-11 19:55 UTC, celian-garcia requested changes

2024-10-11 19:55 UTC, celian-garcia commented on docs/user-guides/oauth-configuration-helpers.md
> +    oauth:
Did you try with oidc? I believe that if oidc works, giving just the issuer URL would be simpler than all the URLs one by one

2024-10-11 19:55 UTC, celian-garcia commented on pkg/model/api/v1/secret/tls_config.go
> +	MinVersion string `yaml:"minVersion" json:"minVersion" default:"TLS12"`
😲 is that default really working? I'd doubt that the config library take it into account. Specially if you use env variable to configure as lamenv library doesn't support it for sure. 
We always use the verify method to setup defaults. I think for the env var and for consistency, we should use the same here.

2024-11-25 09:36 UTC, Nexucis commented
@Labiote would you like to finish this PR ?

2025-01-25 11:14 UTC, Nexucis commented
@Labiote any chance you would like to update this PR ? It's been a while I know and documentations has changed since, but these changes are still accurate I believe.

2025-02-10 10:18 UTC, Nexucis commented
closing this PR in favor of #2619. Thank you for proposing these changes @Labiote.

2025-02-10 10:18 UTC, closed without merging