[FEATURE] Generic Dialog Components
perses/perses pull request #948
Opened 2023-01-30 21:42 UTC by eunicorn

https://github.com/perses/perses/discussions/935

Based on the discussion, we want generic dialog components that include common UX patterns:

1. Close icon button at the top right corner
2. Dividers for dialog content
3. For dialog actions, we always want primary button with contained variant on the left and secondary button (usually Cancel) with outlined variant on the right

2023-01-31 12:26 UTC, celian-garcia requested changes
Great! That would remove already the main duplication issues in the dialogs.

2023-01-31 12:26 UTC, celian-garcia commented on ui/components/src/Dialog/Dialog.tsx
> +export interface DialogButtonProps {
You should probably extend the material ButtonProps here as well, to have all the power of a regular button. 

If you don't want the ``variant`` and ``type`` properties  you can use Omit

```ts
/**
 * following properties are removed from the DialogButtonProps
 */
interface UnwantedButtonProps {
  variant: unknown;
  type: unknown;
}

export interface DialogButtonProps extends Omit<ButtonProps, keyof UnwantedButtonProps> {}
```

2023-01-31 12:26 UTC, celian-garcia commented on ui/components/src/Dialog/Dialog.tsx
> +          sx={(theme) => ({
In the Project CRUD PR, I wrapped this code in a function to optimize rendering performance (an advice from sonarlint). 

I'm not sure it's optimizing that much performances, but I found it clearer at the end. You can go and see if you find it interesting https://github.com/perses/perses/pull/916/files#diff-ce2596b6d1065537010136370c2489af315269aaafa78564f55f9bfd19cd80eeR20-R26

2023-01-31 16:30 UTC, saminzadeh commented on ui/components/src/Dialog/Dialog.tsx
> +  Dialog: MuiDialog,
`Dialog.Dialog` feels bit weird. A few ideas:

```
Dialog.Wrapper
Dialog.Base
```
or just expose this as `Dialog` and only add the sub components.
```tsx
export function Dialog() {...}
Dialog.Header = Header;
```

```tsx
<Dialog>
    <Dialog.Header>My Title</Dialog.Header>
</Dialog>

2023-02-01 10:00 UTC, celian-garcia commented on ui/components/src/Dialog/Dialog.tsx
> +export interface DialogButtonProps extends Omit<ButtonProps, 'variant' | 'color'> {
If you don't put ``type`` in the excluded properties, somebody using it will have some issues no ?

2023-02-02 10:28 UTC, celian-garcia approved these changes

2023-02-02 22:28 UTC, eunicorn commented
@saminzadeh @cndonovan can one of you take another look when you have the chance? thanks!

2023-02-03 17:31 UTC, saminzadeh approved these changes

2023-02-06 16:33 UTC, merged